### ISSUE TITLE
JavaScript fetch blocked by CORS policy

### ISSUE THREAD

**Issue by BrettCrowley77** [wmgeolab/gbWeb#20]
I'm trying to fetch country boundary data in a React component with the following code:

`let REQUEST_STRING =
    "https://www.geoboundaries.org/api/current/gbOpen/EGY/ADM0/";

  let downloadUrl, countryBoundary;

  const fetchBoundaries = async () => {
    try {
      let response1 = await fetch(REQUEST_STRING);
      let response2 = await response1.json();
      let downloadUrl = response2["simplifiedGeometryGeoJSON"];
      let response3 = await fetch(downloadUrl);
      let countryBoundary = await response3.json();
      return;
    } catch (e) {
      console.log(e);
      return null;
    }
  };

  fetchBoundaries();`

The second request is failing with a CORS error:

_Access to fetch at 'https://github.com/wmgeolab/geoBoundaries/raw/905b0ba/releaseData/gbOpen/EGY/ADM0/geoBoundaries-EGY-ADM0.geojson' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://render.githubusercontent.com' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

**Comment by DanRunfola** [comment]
We'll take a look at this - this may be an issue with GitHub, as some of their subdomains don't have the same CORS policies as the main github.com.  That said, I'm not sure why the origin render.githubusercontent.com is in this chain at all.

This may have something to do with our recent transition over to Git LFS, as well.  If that's the case we might have to consider moving our API endpoints on-prem here at W&M, but I hope to avoid that outcome as the bandwidth pressure is pretty substantial (not to mention our mirroring infrastructure is pretty bad).

Anyway - let us take a look and we'll see if we can find a short term solution here.

**Comment by DanRunfola** [comment]
@rohith4444 could you take a peak at this and see if there's anything obvious?

**Comment by DanRunfola** [comment]
Hi @BrettCrowley77 

This has to do with the CORS policy on certain github subdomains, which is something unfortunately out of our control.  Seperately, we're working on a proposal that would fund server resoruces where we could control CORS (or our own CORS proxy), but that's a TBD situation.

In the interim, you can get the code you wrote to work with a CORS proxy - i.e.,:

```
let REQUEST_STRING =
 "https://www.geoboundaries.org/api/current/gbOpen/EGY/ADM0/";

let downloadUrl, countryBoundary;
const fetchBoundaries = async () => {
try {
let response1 = await fetch(REQUEST_STRING);
let response2 = await response1.json();
console.log(response2);
let downloadUrl = response2["simplifiedGeometryGeoJSON"];
let response3 = await fetch('[https://api.allorigins.win/get?url='+](https://api.allorigins.win/get?url=%27+) encodeURIComponent(downloadUrl));
console.log(response3);
let countryBoundary = await response3.json();
return;
} catch (e) {
console.log(e);
return null;
}
};

fetchBoundaries();
```

Wish I had a better answer, but that is unfortunately where GitHub limitations leave us today.

Dan

**Comment by BrettCrowley77** [comment]
Thanks @DanRunfola and team.
