### ISSUE TITLE
Git LFS cases in API

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/gbWeb#4]
Git LFS cases are broken in API - currently link to the LFS marker.

In LFS cases, site to link to needs to follow:

https://media.githubusercontent.com/media/wmgeolab/geoBoundaries/main/releaseData/gbOpen/ESP/ADM3/geoBoundaries-ESP-ADM3.geojson

Currently, all are following:
https://raw.githubusercontent.com/wmgeolab/geoBoundaries/main/releaseData/gbOpen/ESP/ADM3/geoBoundaries-ESP-ADM3.geojson

**Comment by karimbahgat** [comment]
One possible note here. For https://github.com/wmgeolab/geoContrast I ended up just doing all files as LFS, which would simplify not having to check if a boundary is too large or not. This might also be more efficient overall, when I sync large amounts of files on geocontrast it appears to go sort of fast? Though not sure if there's any backdraws to this?

**Comment by DanRunfola** [comment]
Doesn't work for the web links, unfortunately.

**Comment by DanRunfola** [comment]
Fixed with https://github.com/wmgeolab/gbWeb/commit/c991241d4dea7110fb82d16050810da2026c48a9#diff-180eee08c757283d0540a8eaf321f577bfd9021435e504624f120c0bcfd76dd7
